### ISSUE TITLE
prompt_translator.cfg

### ISSUE THREAD

**Issue by Thelastelfl** [butaixianran/Stable-Diffusion-Webui-Prompt-Translator#10]
prompt_translator.cfg文件内容格式是什么样的。。

**Comment by butaixianran** [comment]
用文本编辑器打开看，就是个json文件

**Comment by Thelastelfl** [comment]
没有这个文件，我想要创建文件。但是不知道里面的格式。
{
"provider":"baidu",
"APP ID":"",
"APP KEY":""
}?

**Comment by butaixianran** [comment]
没有的话，你填入app key点击保存不就行了吗

**Comment by Thelastelfl** [comment]
没事了，，我保存一下就行了。。上次没保存，以为需要自己创建。。打扰了。。
