### ISSUE TITLE
请问可以让右上角的“目标语言”的UI底色跟随系统吗？

### ISSUE THREAD

**Issue by NakiriRuri** [butaixianran/Stable-Diffusion-Webui-Prompt-Translator#13]
https://imgur.com/a/9zJSNu8
我相信不是所有用户都使用暗色主题。

**Comment by butaixianran** [comment]
做不到。要做到的话，需要用异常麻烦，近乎hack的做法把前端全部用python重写，不打算做。不过可以把文字颜色强行改白

**Comment by butaixianran** [comment]
已更新，检查新版本，现在改为优先亮色主题，让黑色主题的用户将就

**Comment by NakiriRuri** [comment]
谢谢！
