### ISSUE TITLE
工具栏里的翻译按钮是否没有实现？安装了不起作用

### ISSUE THREAD

**Issue by fridgeman** [butaixianran/Stable-Diffusion-Webui-Prompt-Translator#22]
<img width="257" alt="image" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Prompt-Translator/assets/3667645/66a584b5-df5c-440b-ba6f-690a0c85b675">

https://github.com/butaixianran/Stable-Diffusion-Webui-Prompt-Translator/blob/main/javascript/prompt_translator.js#L129

tab里的翻译是可以用的，也注册了账号

**Comment by butaixianran** [comment]
箭头图标不是翻译按钮，那个是切换中英文显示用的。左边大小写的字幕A的图标，才是翻译按钮。

切换的作用是，你已经翻译过的英文，会覆盖你原本输入的中文。按下这个箭头按钮，就能够切换回中文，或者再切换回英文。
前提是你已经点击过翻译按钮了。

你鼠标放到图标上面，会有提示，告诉你这个按钮是干嘛用的。

本项目的文档中，也有描述和截图，告诉你了这个图标是干嘛用的。

**Comment by fridgeman** [comment]
好的，谢谢
