### ISSUE TITLE
Error in code, MarianMT provider not correct working 

### ISSUE THREAD

**Issue by scan666github** [butaixianran/Stable-Diffusion-Webui-Prompt-Translator#23]
In file _prompt_translator.py_

def MarianMT_trans(text, **lang_pair**):

replace to

def MarianMT_trans(text, **tar_lang**):

**Comment by butaixianran** [comment]
There is no variable `tar_lang` in method `MarianMT_trans`.

If you are not a developer, do not claim something like this as an error.
