### ISSUE TITLE
Question on other api

### ISSUE THREAD

**Issue by piketz** [butaixianran/Stable-Diffusion-Webui-Prompt-Translator#3]
Add yandex api. ran into a problem when translating strings of more than 47 characters api returns the same text. unable to use others

**Comment by butaixianran** [comment]
Hi, this is not a problem of this extension. There is no length limit on text. With deepl or baidu, I can translate about 3000-5000 characters without problem.

You should check yandex API document for that. Or just contact their tech support service.

**Comment by butaixianran** [comment]
I just recalled, I have seen this kind of problem before. That's because it's AI failed to translate your text. You need to try another text to see what happen.

Deepl has the same problem when translating some japanese text. But it works fine in most cases.

**Comment by piketz** [comment]
the problem was when I sent the text in English and adding a word at the end in my language, it was not translated. It turned out that the problem is in the auto-detection of the source language.
**solution**: added an indication of the source language to the request body.

I just don't know what would be better? somewhere in the settings to specify the language selection item or automatically it is somehow possible to snatch the system language from the browser ..

**Comment by butaixianran** [comment]
Do not set the language for user, just let it detect it. If it can not be detected, user will modify their text.

**Comment by piketz** [comment]
awesome! big thank you! this is clearly one of the best extension for sd. all my free time I understood my fork and did not really try to use the translation. It turned out that everything that you write and give translation performs much better than before.
but I still haven't figured out how to pick up the browser's language so as not to use extra libraries.. any ideas? so far I have settled on the fact that there is a Dropdown with a list of popular languages .. but since my programming level is rather low, it is difficult. api fastened and works well, only with the choice of the source language.

**Comment by butaixianran** [comment]
So, help me understand this: why you need this setting? Why auto-detect language does not work for your case?

You know, if you just want to translate another single word after filling English prompt, you can just fill it into negative prompt, translate it, then copy the translated word back into prompt.

**Comment by piketz** [comment]
sorry, but I could not find a normal implementation of the language request. I'll be glad to know where to dig..

these are unnecessary movements .. I just want to add my words to the English promt and send it for automatic translation.

**Comment by butaixianran** [comment]
If most part of text are in English, then it gonna be detected as English. If you set it to other language, translator may not work.

And if you still want that, the only way is by creating a dropdown list, to choose your source language, like on the translator's website.

But this is not needed for most of users, so I won't merge it if you add this feature. You have to do this in your own fork.

**Comment by Torbat** [comment]
> You should check yandex API document for that. Or just contact their tech support service.

Can this extension use Yandex Translator?

**Comment by piketz** [comment]
> Can this extension use Yandex Translator?

yep in my fork.


>But this is not needed for most of users, so I won't merge it if you add this feature. You have to do this in your own fork.

well did that. can be closed issue.

**Comment by butaixianran** [comment]
Before I close this issue, since you are working on a fork, there is a bug in this repo and I fixed it, so you better fix that in your fork too.

in the main python script, change this:
`app_id.visible = trans_providers[key]['has_id']`
to this:
`app_id.visible = trans_providers[provider_name]['has_id']`

**Comment by butaixianran** [comment]
And now, this can be closed
