### ISSUE TITLE
toolbar不显示 

### ISSUE THREAD

**Issue by zpengcom** [butaixianran/Stable-Diffusion-Webui-Prompt-Translator#5]
toolbar 没显示 是不是要在用户界面加什么参数？

**Comment by butaixianran** [comment]
不需要，没显示，说明插件根本没有运行。查看控制台，有没有什么报错

toolbar是javascript写的，所以是不会报错的，只要插件运行了，就一定会运行。

因此，如果你的webui因为别的原因，在加载本插件之前，就出错了，才比较可能导致这种问题。关键看控制台给出什么报错。完整的，不要只有最后一句话。

**Comment by butaixianran** [comment]
另外，想请问一下，你是不是用的什么国内网盘版本的stable diffusion webui? 或者国内提供的什么启动包、安装包之类的？

如果是，你的stable diffusion webui可能是很老很老的版本。它会停留在那个包最初打包时的那个版本，永不变动。

因此，如果你是这种情况，请提供你的stable diffusion webui版本号。版本号在stable diffusion webui运行后，网页最下方，有个叫：commit hash字符串的地方。那个字符串就是版本号。

**Comment by zpengcom** [comment]
> 另外，想请问一下，你是不是用的什么国内网盘版本的stable diffusion webui? 或者国内提供的什么启动包、安装包之类的？
> 
> 如果是，你的stable diffusion webui可能是很老很老的版本。它会停留在那个包最初打包时的那个版本，永不变动。
> 
> 因此，如果你是这种情况，请提供你的stable diffusion webui版本号。版本号在stable diffusion webui运行后，网页最下方，有个叫：commit hash字符串的地方。那个字符串就是版本号。

就用的原版  启动加了git pull 所以应该就是最新的 安装插件后有一个错误是提示没有配置文件，添加配置后 没有看到错误了，

python: 3.10.10  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2  •  commit: [0cc0ee1b]


刚才试了下 **语言设置**  然后复现了这个问题，之前我用的是中+英的第三方配置文件，（我猜你是不是加载时作了页面语言的判断），切换成zh-cn的配置文件就正常了

**Comment by butaixianran** [comment]
toolbar是需要取到tab名字的，不过是自适应所有语言的。

应该是那个中+英的语言包的问题。

不确定你的中+英语言包是怎么来的。webui是单语言的，必须选择他支持的语言国别code，应该是不能设置双语界面的。
