### ISSUE TITLE
Promt not translate

### ISSUE THREAD

**Issue by iqubik** [butaixianran/Stable-Diffusion-Webui-Prompt-Translator#6]
Automatic1111 if i write in promt RUS - "тест" all be blank

**Comment by iqubik** [comment]
Getting data for deepl
app_key can not be empty

**Comment by iqubik** [comment]
TAb

**Comment by butaixianran** [comment]
So, you already know the reason, it tells you, you need to fill deepl's app_key and save it in this addon.

This project's readme page has already told you how to do it. Read the "how to use" section.
