### ISSUE TITLE
Add AI translate 

### ISSUE THREAD

**Issue by piketz** [butaixianran/Stable-Diffusion-Webui-Prompt-Translator#8]
I have added AI translation to my fork, Helsinki-NLP https://huggingface.co/Helsinki-NLP

But I also added a language selection item there.
you can use a multi model for translation, I just don't know how good it is.
you can use it without additional requests through various API.
For my language it works quite well.
Why didn't you go down this path? because sd uses torch and adding it was not a problem.
I haven't fully tested it yet, but I haven't found any bugs on the current commit..

**Comment by butaixianran** [comment]
ok, this is a lot of information here. I'll take some time to check it out. Since I'm not sure the quality of its translation result, it gonna take some time for trying.  

Also, as you mentioned, it is a good choice to do this in your own fork. 

About cloud based translation service, they are easy to use, easy to develop with, up to date, and 100% free for this extension. You should know that, those who need this extension, are not good at English and unlikely to read a document then set their own local translation engine.

**Comment by Shestoperd** [comment]
> About cloud based translation service, they are easy to use, easy to develop with, up to date, and 100% free for this extension.

Looks like Deepl no longer gives free translation. I tried to get a Deepl PRO trial but my country is not listed.
Other services are very confusing.
Being able to translate without being tied to online services looks very attractive.

**Comment by butaixianran** [comment]
Deepl API free plan is always there. you are looking the wrong page.

you need go to the API plan page, not the normal user plan page.

There is a very big button named as API at the top of deepl's page.

**Comment by Shestoperd** [comment]
> There is a very big button named as API at the top of deepl's page.

I tried, but the "sign up for free" button does nothing. Checked two different browsers, and cell phone, tried through a VPN, no way to subscribe to this service. Apparently for my country this service is not available, as well as payment.
I think it's very good to be able to not depend on the whims of online services, which at any time can make their services paid.

**Comment by butaixianran** [comment]
ok, I'll see what I can do, I haven't tested this local translation model yet.

**Comment by butaixianran** [comment]
also, if your country has free online market like ebay, you can buy a deepl API free account, even your country can not use its service. Pay once, free forever.

In China, people are selling deepl's free API account for 5 dollars.

**Comment by butaixianran** [comment]
I tested this local model, for articles, its quality is pretty bad between Chinese and English, like a cloud translation service 20 years before. The translated article is very hard to read.

On the other hand, cloud translation service like deepl or baidu, can translate the same article with a quality like magic.

But, with prompt which is just a group of words, it offers an ok level result.

In that case, I'll add it into this extension, but with limited support.

**Comment by piketz** [comment]
what model was tested? Chinese or Multiple languages .. they gave me different answers to a request in Russian "Привет" one gives out "Hey." or "hello".
https://huggingface.co/Helsinki-NLP/opus-mt-mul-en
https://huggingface.co/Helsinki-NLP/opus-mt-zh-en
https://huggingface.co/Helsinki-NLP/opus-mt-ru-en
you can check right there.

**Comment by butaixianran** [comment]
I tested zn-en and en-zh. I don't use the multiple languages one. Like I mentioned, will be added, limited support. They are not so good compare to cloud service, which has a development team keeps working on their models and offers it for free in this case.

**Comment by Shestoperd** [comment]
> But, with prompt which is just a group of words, it offers an ok level result.
> 
> In that case, I'll add it into this extension, but with limited supportС.

Thank you. For our purposes, such a translation will be sufficient, in addition, you can download different models for translation, by analogy with different models for generating images.
You can use Midjourney, because it works better than Stable Diffusion, and is completely free, but still we install Stable Diffusion ;)

**Comment by butaixianran** [comment]
MarianMT is supported. Check document for usage. 

No more feature request about MarianMT.

**Comment by Shestoperd** [comment]
Thank you so much, this is a good alternative to online translators.
You can use this [page to quickly find the language](https://huggingface.co/models?language=en,zh&sort=downloads&search=helsinki) you need.
On the left, select the desired languages, and on the right there will be a list of all models that contain these languages.

**Comment by butaixianran** [comment]
ok, I'll treat this as done.
