### ISSUE TITLE
languages  from/to support

### ISSUE THREAD

**Issue by sxlwzl** [butaixianran/Stable-Diffusion-Webui-Prompt-Translator#9]
request_link = trans_providers["baidu"]["url"]+"?q="+text+"&from=en&to=zh&appid="+app_id+"&salt="+salt+"&sign="+sign_md5

currently, from/to is fixed, can you support manual select options. 

Thanks,
sxlwzl

**Comment by butaixianran** [comment]
what is the meaning of that?

Source language is auto detected. Target language will always be english which is the only language SD accept.

So, why you need to choose it manually?

**Comment by sxlwzl** [comment]
when we copy some prompts from other site, like C, we may need to know the meaning. Maybe you can add a choice for this usage.

Thanks,
sxlwzl

**Comment by butaixianran** [comment]
I'll see what I can do. If every translation service uses a different language code then I may not do it.

**Comment by butaixianran** [comment]
Done. Added supporting for selecting target lanuage. Update your extension.

Source language is still auto detected. As your description, there is no need to select source language manually. Auto detected is good enough.
